import { Transform, Type } from "class-transformer"
import { IsNotEmpty, IsString, Length } from "class-validator"
import { ITenant, Tenant } from "../domain/entities/tenant"
import { uuidv7 } from "uuidv7"
import { TenantStatus } from "../domain/valueObjects/tenant-status.enum"
import { env } from "process"
